FROM node:14-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY services/dashboard_service ./

RUN npm install

RUN npm install -g serve

RUN npm run build

CMD ["serve", "-s", "build"]