FROM python:3.8

WORKDIR /app

COPY services/analytics_service ./

RUN pip install -r requirements.txt

CMD ["gunicorn", "main:app", "-b 0.0.0.0:8000", "-w", "8", "-k", "uvicorn.workers.UvicornWorker"]